- name: "Play: Create VMs on Chameleon"
  hosts: LocalMC  # This corresponds to the alias in your inventory
  remote_user: "{{ local_user }}"
  gather_facts: no
  become: false

  vars_files:
    - Users/sanjanadas/ansible_gen/AnsibleAutomation/test_vars.yml  # Adjust the path according to your directory structure

  vars:
    ansible_python_interpreter: /Users/sanjanadas/ansible_gen/AnsibleAutomation/myvenv/bin/python3.11
  tasks:
    - import_tasks: tasks/playbook_create_vm.yaml
