---
- name: "Play 13C:  Start a new K8s clusters on designated masters"
  hosts: "{{ K8s['masters_inv'] }}[0:{{ (K8s['clusters']*K8s['masters'] - 1) }}]"       # specified in our vars yaml file
  remote_user:  "{{ cloud['user'] }}"      # note that the user is cc on Chameleon
  #become: true  # we do this per individual task
  gather_facts: yes # we need this to map public IP to private IP
  collections:
  - ansible-base

  tasks:    # the task to be performed
  - name: "Set additional cmd line options "
    ansible.builtin.set_fact:
      option: "{{ '--skip-phases=addon/kube-proxy' if K8s['cni']  == 'cilium' else '' }}"
      
  - name: "Executing command to start K8s cluster primary master on this node"
    ansible.builtin.debug:
      msg: kubeadm init --apiserver-advertise-address {{ ansible_facts['default_ipv4']['address'] }} --control-plane-endpoint {{ ansible_facts['default_ipv4']['address'] }} --service-cidr 10.{{ (80 + (groups[K8s['masters_inv']].index (inventory_hostname) // K8s['masters']) + 1)|string }}.0.0/16 --pod-network-cidr={{ K8s['pod_network'] }} {{ option }}
    when: "((groups[K8s['masters_inv']].index (inventory_hostname) % K8s['masters']) == 0)"
...

