---
#
# EECS 4287/5287: Principles of Cloud Computing
# CS/ECE 4383/5383: Computer Networking
# Author: Aniruddha Gokhale
# Created: Spring 2023
# Modified: Fall 2023
#
# Here we restart containerd

  # Now restart the daemon
  - name: "Next, reload and restart containerd"
    ansible.builtin.systemd:
      name: containerd
      daemon_reload: true
      state: restarted
      
...
