---
#
# CS/ECE 4383/5383: Computer Networks
# Author: Aniruddha Gokhale
# Created: Fall 2023 based on similar playbooks created before.
#
# This playbook will create VMs as specified on the desired cloud platform
# See https://docs.ansible.com/ansible/latest/collections/openstack/cloud/server_module.html
#
# Despite the numerous amount of commonality, to save time, I am repeating the steps
# for the Bastion, K8s masters, and K8s workers

  - name: "Create Bastion VM on the Cloud"
    openstack.cloud.server:
      cloud: "{{ cloud['name'] }}"   # which cloud
      state: present   # i.e., create
      availability_zone: "{{ cloud['zone'] }}"  # which availability zone
      # a complex naming scheme using loop index variable
      name: "{{ cloud['name_prefix'] + \"Bastion\" }}"
      boot_from_volume: false
      image: "{{ cloud['image'] }}"  # indicates the image used to boot
      flavor: "{{ cloud['bastion_flavor'] }}" # what flavor
      key_name: "{{ cloud['bastion_key'] }}" # what key to use
      security_groups:  "{{ cloud['bastion_security_groups'] }}"  # which security groups
      network: "{{ cloud['bastion_network'] }}"  # network name
      # nics: "net-id: {{ cloud['netid'] }}"  # which network interface (supply either network or nics)
      #auto_ip: false   # we force an IP address (cannot be used when using floating_ips)
      floating_ips: "{{ cloud['bastion_fip'] }}"    # what floating IP
      reuse_ips: false
      wait: yes  # this is the default
      description: "Bastion VM"
      #timeout: 300 # wait 5 mins for the instance to get into active state


###############################################################
#  The connection waiting is usually right after the action
###############################################################
  - name : "Wait for Connection to VM"
    ansible.builtin.wait_for_connection:
...


