---
#
# CS/ECE 4383/5383: Computer Networks
# Author: Aniruddha Gokhale
# Created: Fall 2023
#

# In this playbook we create a open virtual switch bridge on each cluster master

  - name: "Debug: Delete ovs bridge per team per cluster master"
    ansible.builtin.debug:
      msg: "sudo ovs-vsctl add-br {{ item }}_cluster{{ (groups[K8s['masters_inv']].index (inventory_hostname) + 1) }}"
    loop: "{{ K8s['teams'] }}"
    # Add such condition when needed, here I added a team later on
    #when: item == "instr_ta"

  - name: "First, delete any older ovs bridge of that name per team per cluster master"
    openvswitch.openvswitch.openvswitch_bridge:   
      bridge: "{{ item }}_cluster{{ (groups[K8s['masters_inv']].index (inventory_hostname) + 1) }}"
      state: absent
    loop: "{{ K8s['teams'] }}"

...
