---
#
# EECS 4287/5287: Principles of Cloud Computing
# CS/ECE 4383/5383: Computer Networking
# Author: Aniruddha Gokhale
# Created: Spring 2023
# Modified: Fall 2023
#
# Here we restart docker daemon

  # Now restart the daemon
  - name: "Reload and restart docker.service"
    ansible.builtin.systemd:
      name: docker
      daemon_reload: true
      state: restarted
      
...
