---
#
# CS/ECE 4383/5383: Computer Networks
# Author: Aniruddha Gokhale
# Created: Fall 2023
#
# Here we delete namespaces on each cluster for each team
# 
  - name: "Debug:Delete K8s namespace per team"
    ansible.builtin.debug:
      msg: "kubectl delete namespace cluster{{ (groups[K8s['masters_inv']].index (inventory_hostname) + 1)|string }}-{{ item | replace ('_','-') }}"
    loop: "{{ K8s['teams'] }}"

  - name: "Delete any prior K8s namespace of that name"
    kubernetes.core.k8s:
      name: "cluster{{ (groups[K8s['masters_inv']].index (inventory_hostname) + 1)|string }}-{{ item | replace ('_', '-') }}"
      api_version: v1
      kind: Namespace
      state: absent
#      wait: true
    loop: "{{ K8s['teams'] }}"

...
